#!/bin/bash
# scripts/install-simple.sh — 简化安装（不依赖 TeamWiseFlow 父仓库 release）
#
# 与 scripts/install.sh 的区别：
#   - install.sh        → 从父仓库 release 拉预构建 tarball（需要 TeamWiseFlow 发布 release）
#   - install-simple.sh → 直接用我们 fork 的 master + OpenClaw upstream partial assets
#   - install-simple.sh 不装微信插件 / camoufox-cli，只装最小可跑的 daemon

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
WUTONGHUI_ROOT="${WUTONGHUI_HOME:-$HOME/wutonghui-xiaobei}"
OPENCLAW_HOME="${OPENCLAW_HOME:-$HOME/.openclaw}"

echo "========================================"
echo "  wutonghui-xiaobei 简化安装"
echo "  时间：$(date)"
echo "========================================"
echo ""
echo "  WUTONGHUI_ROOT (程序)：$WUTONGHUI_ROOT"
echo "  OPENCLAW_HOME   (数据)：$OPENCLAW_HOME"
echo ""

# ---- Phase 1: 下载 OpenClaw 二进制 ----
echo "[Phase 1] 下载 OpenClaw 上游 zip（带 daemon）"

# 尝试多个源
download_openclaw() {
    local url="$1"
    local out="$2"
    if curl -L -o "$out" -m 300 --retry 5 -w "Download: %{size_download} bytes / %{time_total}s\n" "$url" 2>&1 | grep -q "Download:"; then
        if [ "$(stat -f%z "$out" 2>/dev/null || echo 0)" -gt 100000000 ]; then
            return 0
        fi
    fi
    return 1
}

TMP_ZIP="/tmp/wth-oc.zip"
if [ ! -f "$TMP_ZIP" ] || [ "$(stat -f%z "$TMP_ZIP" 2>/dev/null || echo 0)" -lt 100000000 ]; then
    echo "  尝试 GitHub releases（OpenClaw upstream）..."
    if ! download_openclaw \
        "https://github.com/openclaw/openclaw/releases/download/v2026.9.8/OpenClaw-2026.9.8-arm64.zip" \
        "$TMP_ZIP"; then
        echo "  ✗ GitHub 下载失败，尝试 gh release..."
        gh release download -R openclaw/openclaw \
            -p "OpenClaw-2026.9.8-arm64.zip" \
            -D /tmp --skip-existing
        mv /tmp/OpenClaw-2026.9.8-arm64.zip "$TMP_ZIP" 2>/dev/null || true
    fi
fi

if [ "$(stat -f%z "$TMP_ZIP" 2>/dev/null || echo 0)" -lt 100000000 ]; then
    echo "  ✗ 下载失败（可能 GitHub 限速），跳过 §5 daemon 装"
    echo "  建议：手动下载 OpenClaw-2026.9.8-arm64.zip 到 /tmp/wth-oc.zip 后重跑"
    exit 1
fi
echo "  V 下载完成: $(stat -f%z "$TMP_ZIP") 字节"
echo ""

# ---- Phase 2: 解压到 WUTONGHUI_ROOT ----
echo "[Phase 2] 解压到 $WUTONGHUI_ROOT"
mkdir -p "$WUTONGHUI_ROOT"
# 清空旧内容（保留 data 子目录）
rm -rf "$WUTONGHUI_ROOT"/*
unzip -q -o "$TMP_ZIP" -d "$WUTONGHUI_ROOT" 2>&1 | head -3
echo "  V 解压完成"
echo ""

# ---- Phase 3: 复制 fork 的 crews/skills/awada/config-templates ----
echo "[Phase 3] 复制 fork 的 crews/skills/awada/config"
for d in crews skills config-templates awada patches; do
    if [ -d "$ROOT/$d" ]; then
        cp -R "$ROOT/$d" "$WUTONGHUI_ROOT/$d/"
        echo "  V $d"
    fi
done
echo ""

# ---- Phase 4: 初始化 OPENCLAW_HOME ----
echo "[Phase 4] 初始化 $OPENCLAW_HOME"
mkdir -p "$OPENCLAW_HOME"

# 复制 config 模板
cp -R "$ROOT/config-templates/." "$OPENCLAW_HOME/" 2>/dev/null || true

# 写 daemon.env
cat > "$OPENCLAW_HOME/daemon.env" << 'EOF'
# OpenClaw daemon env (auto-generated by wutonghui install-simple.sh)
WUTONGHUI_HOME=$WUTONGHUI_ROOT
OPENCLAW_HOME=$OPENCLAW_HOME
EOF

# 写 openclaw.json（最简配置）
cat > "$OPENCLAW_HOME/openclaw.json" << 'EOF'
{
  "version": "1.0.0",
  "crews_dir": "$WUTONGHUI_ROOT/crews",
  "skills_dir": "$WUTONGHUI_ROOT/skills",
  "channel": "awada",
  "mock_mode": true
}
EOF
echo "  V OPENCLAW_HOME 已初始化"
echo ""

# ---- Phase 5: 启动 daemon ----
echo "[Phase 5] 启动 daemon"
DAEMON_BIN="$WUTONGHUI_ROOT/bin/openclaw"
if [ ! -f "$DAEMON_BIN" ]; then
    echo "  ✗ 找不到 daemon 二进制: $DAEMON_BIN"
    echo "  请检查 $WUTONGHUI_ROOT/bin/ 目录"
    exit 1
fi

# 启动 daemon（前台）
echo "  启动: $DAEMON_BIN gateway run --port 18789 --host 127.0.0.1"
echo ""
echo "========================================"
echo "  ✓ 安装完成！"
echo "========================================"
echo ""
echo "下一步："
echo "  bash scripts/test-desktop.sh   # 启动桌面 GUI"
echo ""

